In [ ]:
# import scraper function from reviews_core
from reviews_core.scraper import scrape_new_reviews
from reviews_core.cleaning import clean_new_reviews, update_df_clean
from reviews_core.apply_bertopic import bertopic_cleaning, apply_bertopic
from reviews_core.update_final_dataframes import update_df_monthly, update_df_topic

In [ ]:
scrape_new_reviews()

In [ ]:
clean_new_reviews()

In [ ]:
update_df_clean()

In [92]:
bertopic_cleaning()

Shape before dropping reviews with less than 4 words: (2425, 6)
Shape after dropping reviews with less than 4 words: (1545, 6)
Shape of new_df_clean before bertopic cleaning: (1545, 6)
Shape of new_df_clean after bertopic cleaning: (1543, 7)

,app,score,review_text,review_date,scrape_date,word_count,bert_review_text
0,Santander,1,balance not refreshing to new amount and its not pending live chat takes tooo long for anything,2025-11-03 12:07:26+00:00,2025-11-05 11:38:29.709537+00:00,17,balance not refreshing to new amount and its not pending live chat takes tooo long for anything
1,Santander,2,disappointing so far ... am failing to log into my Açcount for first time.,2025-11-02 17:12:59+00:00,2025-11-05 11:38:29.709537+00:00,14,so far ... am failing to log into my Açcount for first time.
2,Santander,4,once you suss it out it's quite easy to use.,2025-11-02 16:30:26+00:00,2025-11-05 11:38:29.709537+00:00,10,once you suss it out it's quite easy to use.
3,Santander,1,"Cannot open the Santander app due to it needing an update, but when I try to download the update, it just keeps pending as if it is downloading but never actually downloads, so I cannot even get into my banking.",2025-11-02 12:04:23+00:00,2025-11-05 11:38:29.709537+00:00,40,"Cannot open the due to it needing an update, but when I try to download the update, it just keeps pending as if it is downloading but never actually downloads, so I cannot even get into my ."
4,Santander,2,"Still showing ""refunds pending"" when i have already been refunded. > does not refresh! & show the correct information on pending transactions.",2025-11-02 07:33:29+00:00,2025-11-05 11:38:29.709537+00:00,22,"Still showing ""refunds pending"" when i have already been refunded. > does not refresh! & show the correct information on pending transactions."
...,...,...,...,...,...,...,...
1540,Monzo,5,lovely app and great banking tools,2025-10-22 17:56:12+00:00,2025-11-05 11:38:29.709537+00:00,6,lovely and great tools
1541,Monzo,5,the best. ive ever had.,2025-10-22 10:10:00+00:00,2025-11-05 11:38:29.709537+00:00,5,the . ive ever had.
1542,Monzo,5,reliable and easy to use,2025-10-21 17:44:25+00:00,2025-11-05 11:38:29.709537+00:00,5,reliable and easy to use
1543,Monzo,1,"Startup Unfriendly I want to switch banks from another bank with high fees. Having spent 30 minutes they reject the application with no real explanation. This is a retail company. You take away the utility of in-person banking by not allowing me to explain away issues, but completely wasted 30 mins and my having to click on your QR code, this link and that link.",2025-10-21 11:54:14+00:00,2025-11-05 11:38:29.709537+00:00,65,"Startup Unfriendly I want to switch banks from another with high fees. Having spent 30 minutes they reject the application with no real explanation. This is a retail company. You take away the utility of in-person by not allowing me to explain away issues, but completely wasted 30 mins and my having to click on your QR code, this link and that link."
1544,Monzo,3,"pretty good except..... unable to delete archived pots so that's quite annoying, also it starts the Android game engine for some reason? I had to go into the games app and remove it from the list.",2025-10-20 17:11:54+00:00,2025-11-05 11:38:29.709537+00:00,36,"pretty good except..... unable to delete archived pots so that's quite annoying, also it starts the Android game engine for some reason? I had to go into the games and remove it from the list."

In [ ]:
apply_bertopic()

Batches:   0%|          | 0/49 [00:00<?, ?it/s]

2025-11-05 15:05:04,290 - BERTopic - Predicting topic assignments through cosine similarity of topic and document embeddings.

Applied BERTopic model. Shape of new_df_topics: (1543, 9)
Shape before removing 'Outliers' and 'Undefined': (1543, 10)
Shape after removing 'Outliers' and 'Undefined': (1341, 10)

In [ ]:
update_df_monthly()

In [98]:
update_df_topic()

Existing df_topic shape: (223787, 9)
New df_topics shape: (1341, 10)
✅ Updated df_topic saved to ../assets/df_topic.parquet. New shape: (225128, 10)

,subset,app,score,review_text,review_date,word_count,bert_macro_label,bert_label,bert_probs,scrape_date
0,train,Santander,2,extremely irritating that you can't use an older version of this app. the new version takes up much to space for a banking app,2025-10-20 08:36:34,24,User Experience,Layout & Interface,0.108572,NaT
1,train,Santander,4,"Please stop forcing us to update the app. This happens far too often and is annoying. Quickly check your balance? No, impossible until you've wasted time downloading and then installing an unwanted upgrade.",2025-10-19 16:10:13,33,Money Management,Money Management,0.111889,NaT
2,train,Santander,1,"Don't install the latest update on Pixel 3. It crashes when you click on some open banking links. I have tried to provide the crash dump to no avail. Still waiting for ""feedback"" after 1 month.",2025-10-18 14:37:18,36,Performance,Stability,1.000000,NaT
3,train,Santander,4,"I've dropped my review because since the app change, my quick balance has vanished. I shall reinstate my 5 stars when I get my quick balance back. It's back. Back to 4 stars. Good app.",2025-10-17 19:39:21,35,Money Management,Money Management,0.258466,NaT
4,train,Santander,2,Good app generally but paying in cheques is designed by an evil person. Especially if you have a blank 2nd side. Annoyed me thoroughly,2025-10-17 14:01:33,24,Products,Cheque,0.443188,NaT
...,...,...,...,...,...,...,...,...,...,...
225123,new reviews,Monzo,1,saying server issues while opening new account,2025-10-22 17:58:10,7,Login & Authentication,Login & Authentication,0.420496,2025-11-05 11:38:29.709537
225124,new reviews,Monzo,5,lovely app and great banking tools,2025-10-22 17:56:12,6,User Experience,Simplicity,0.477018,2025-11-05 11:38:29.709537
225125,new reviews,Monzo,5,reliable and easy to use,2025-10-21 17:44:25,5,Performance,Reliability,0.742906,2025-11-05 11:38:29.709537
225126,new reviews,Monzo,1,"Startup Unfriendly I want to switch banks from another bank with high fees. Having spent 30 minutes they reject the application with no real explanation. This is a retail company. You take away the utility of in-person banking by not allowing me to explain away issues, but completely wasted 30 mins and my having to click on your QR code, this link and that link.",2025-10-21 11:54:14,65,Money Management,Money Management,0.472734,2025-11-05 11:38:29.709537
225127,new reviews,Monzo,3,"pretty good except..... unable to delete archived pots so that's quite annoying, also it starts the Android game engine for some reason? I had to go into the games app and remove it from the list.",2025-10-20 17:11:54,36,Performance,Stability,0.505137,2025-11-05 11:38:29.709537